### ISSUE TITLE
AFC - put_path doesn't work with directories.

### ISSUE THREAD

**Issue by tuckerwales** [adamely/idevice#1]
afc.put_path doesn't work when trying to place a directory.

**Comment by emonti** [comment]
Isn't afc.mkdir what you want here? (serious question, put another way, what's the expected behavior for put_path?)

**Comment by tuckerwales** [comment]
mkdir makes a directory - it doesn't copy a directory recursively.

put_path should be able to traverse down directories:

Copying of a .app, for example, will not work because it is a directory.

**Comment by emonti** [comment]
ah ok, I kind-of left recursive AFC operations out intentionally (or left as an exercise to the implementor). That said, it's pretty easy to add one for put_path -- it gets uglier when you want to recursively get, remove, or rename over afc, though. 

I'll add an AFC.put_recursively and some argument handling to make it work via put_path. But i think the default behavior should still be to operate without recursing.

On the subject of recursing via AFC, though:
I did some digging around in the afc server binary and found out there are several AFC message types which are not (yet?) implemented in libimobiledevice that might help here, though. I'll look into getting these added to libimobiledevice, but it's ultimately up to them whether to add support...

```
#define GetSizeOfPathContents   0x21
#define RemovePathAndContents   0x22
#define DirectoryEnumeratorRefOpen          0x23
#define DirectoryEnumeratorRefOpenResult    0x24
#define DirectoryEnumeratorRefRead          0x25
#define DirectoryEnumeratorRefClose         0x26
```

**Comment by emonti** [comment]
Ok, recursive put support is added as of idevice v1.1.5.6

to use it, either do

```
afc.put_recursively("somelocaldir", "someremotediralreadyexists/")
```

or
    afc.put_path("somelocaldir", "someremotediralreadyexists/", recurse: true)

as for recursive get/remove/rename -- those are still left un-implemented pending seeing what happens with adding support for the additional native code AFC operations

**Comment by emonti** [comment]
minor tweak added for v1.1.5.7 -- absolute local paths weren't handled correctly, they should be now. Sorry, i should have tested, but i don't want to add rspec device tests until we get recursive removes working, it'll leave crap all over the device... =/
